### ISSUE TITLE
Error establishing a database connection

### ISSUE THREAD

**Issue by satell** [srvk/lm_build#2]
when I try to open your website by this link ,  

http://speechkitchen.org/

I get this error "Error establishing a database connection" is your website down ? could you please fix it ? 

regards 
Ehsan

**Comment by riebling** [comment]
We're working on a problem with the MySQL server, whereby it keeps shutting down. Sorry about that!

**Comment by riebling** [comment]
Think we've fixed the MySQL persistence problem.
